# dictonary initialization 
dictionary = {}

# filling dictionary with data 
dictionary = {'variable':['title', 'center', 'project_id', 'experiment_id',
                          'sample_id ', 'run_id’, ‘platform ', 'model ', 'organism ', 'sequence_type',
                          'run_id', 'read_count', 'base_count', 'run_id', 'feature_id', 'kingdom',
                          'phylum', 'class', 'orders', 'family', 'genus', 'species', 'confidence',
                          'sample_id', 'acid_reflux', 'acne_medication', 'acne_medication_otc',
                          'add_adhd', 'age_cat', 'age_corrected', 'age_years', 'alcohol_consumption',
                          'alcohol_frequency', 'alcohol_types', 'alcohol_types_beercider',
                          'alcohol_types_red_wine', 'alcohol_types_sour_beers',
                          'alcohol_types_spiritshard_alcohol', 'alcohol_types_unspecified',
                          'alcohol_types_white_wine', 'allergic_to',
                          'allergic_to_i_have_no_food_allergies_that_i_know_of', 'allergic_to_other',
                          'allergic_to_peanuts', 'allergic_to_shellfish', 'allergic_to_tree_nuts',
                          'allergic_to_unspecified', 'altitude', 'alzheimers', 'anonymized_name',
                          'antibiotic_history', 'appendix_removed', 'artificial_sweeteners', 'asd',
                          'assigned_from_geo', 'autoimmune', 'birth_year', 'bmi', 'bmi_cat',
                          'bmi_corrected', 'body_habitat', 'body_product', 'body_site',
                          'bowel_movement_frequency', 'bowel_movement_quality',
                          'breastmilk_formula_ensure', 'cancer', 'cancer_treatment',
                          'cardiovascular_disease', 'cat', 'cdiff', 'census_region',
                          'chickenpox', 'clinical_condition', 'collection_date',
                          'collection_month', 'collection_season', 'collection_time',
                          'collection_timestamp', 'consume_animal_products_abx', 'contraceptive',
                          'cosmetics_frequency', 'country', 'country_of_birth', 'country_residence',
                          'csection', 'deodorant_use', 'depression_bipolar_schizophrenia', 'depth',
                          'diabetes', 'diabetes_type', 'diet_type', 'dna_extracted', 'dog',
                          'dominant_hand', 'drinking_water_source', 'drinks_per_session',
                          'economic_region', 'elevation', 'env_biome', 'env_feature', 'env_material',
                          'env_package', 'epilepsy_or_seizure_disorder', 'exercise_frequency',
                          'exercise_location', 'fed_as_infant', 'fermented_plant_frequency',
                          'flossing_frequency', 'flu_vaccine_date', 'frozen_dessert_frequency',
                          'fruit_frequency', 'fungal_overgrowth', 'geo_loc_name', 'gluten',
                          'has_physical_specimen', 'height_cm', 'height_units',
                          'high_fat_red_meat_frequency', 'homecooked_meals_frequency',
                          'host_common_name', 'host_subject_id', 'host_taxid', 'ibd', 'ibd_diagnosis',
                          'ibd_diagnosis_refined', 'ibs', 'kidney_disease', 'lactose', 'last_move',
                          'last_travel', 'latitude', 'level_of_education', 'liver_disease',
                          'livingwith', 'longitude', 'lowgrain_diet_type', 'lung_disease',
                          'meat_eggs_frequency', 'mental_illness', 'mental_illness_type',
                          'mental_illness_type_anorexia_nervosa',
                          'mental_illness_type_bipolar_disorder', 'mental_illness_type_bulimia_nervosa',
                          'mental_illness_type_depression',
                          'mental_illness_type_ptsd_posttraumatic_stress_disorder',
                          'mental_illness_type_schizophrenia', 'mental_illness_type_substance_abuse',
                          'mental_illness_type_unspecified', 'migraine', 'milk_cheese_frequency',
                          'milk_substitute_frequency', 'multivitamin', 'nail_biter', 'non_food_allergies',
                          'non_food_allergies_beestings', 'non_food_allergies_drug_eg_penicillin',
                          'non_food_allergies_pet_dander', 'non_food_allergies_poison_ivyoak',
                          'non_food_allergies_sun', 'non_food_allergies_unspecified', 'olive_oil',
                          'one_liter_of_water_a_day_frequency', 'other_supplement_frequency',
                          'pets_other', 'physical_specimen_location', 'physical_specimen_remaining',
                          'pku', 'pool_frequency', 'poultry_frequency', 'pregnant',
                          'prepared_meals_frequency', 'probiotic_frequency', 'public', 'race',
                          'ready_to_eat_meals_frequency', 'red_meat_frequency', 'roommates',
                          'roommates_in_study', 'salted_snacks_frequency', 'sample_type',
                          'seafood_frequency', 'seasonal_allergies', 'sex', 'sibo', 'skin_condition',
                          'sleep_duration', 'smoking_frequency', 'softener', 'specialized_diet',
                          'specialized_diet_exclude_dairy', 'specialized_diet_exclude_nightshades',
                          'specialized_diet_exclude_refined_sugars', 'specialized_diet_fodmap',
                          'specialized_diet_halaal', 'specialized_diet_i_do_not_eat_a_specialized_diet',
                          'specialized_diet_kosher', 'specialized_diet_modified_paleo_diet',
                          'specialized_diet_other_restrictions_not_described_here',
                          'specialized_diet_paleodiet_or_primal_diet', 'specialized_diet_raw_food_diet',
                          'specialized_diet_unspecified',
                          'specialized_diet_westenprice_or_other_lowgrain_low_processed_fo', 'state',
                          'subset_age', 'subset_antibiotic_history', 'subset_bmi', 'subset_diabetes',
                          'subset_healthy', 'subset_ibd', 'sugar_sweetened_drink_frequency',
                          'sugary_sweets_frequency', 'survey_id', 'teethbrushing_frequency', 'thyroid',
                          'title', 'tonsils_removed', 'types_of_plants', 'vegetable_frequency',
                          'vitamin_b_supplement_frequency', 'vitamin_d_supplement_frequency',
                          'vivid_dreams', 'weight_change', 'weight_kg', 'weight_units', 'whole_eggs',
                          'whole_grain_frequency', 'name', 'nucleotide', 'protein', 'pubmed'],
              'table':['project', 'project', 'project', 'experiment', 'experiment', 'experiment',
                       'experiment', 'experiment', 'experiment', 'experiment', 'run', 'run', 'run',
                       'organisms', 'organisms', 'organisms', 'organisms', 'organisms', 'organisms',
                       'organisms', 'organisms', 'organisms', 'organisms', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'sample',
                       'sample', 'sample', 'sample', 'sample', 'sample', 'sample', 'phylum', 'phylum',
                       'phylum', 'phylum'],
              'data_type':['VARCHAR(30)', 'VARCHAR(30)', 'VARCHAR(30)', 'VARCHAR(30)', 'VARCHAR(30)',
                           'VARCHAR(30)', 'VARCHAR(30)', 'VARCHAR(30)', 'VARCHAR(30)', 'VARCHAR(30)',
                           'VARCHAR(30)', 'INT', 'INT', 'VARCHAR(30)', 'VARCHAR(50)', 'VARCHAR(30)',
                           'VARCHAR(30)', 'VARCHAR(30)', 'VARCHAR(30)', 'VARCHAR(30)', 'VARCHAR(30)',
                           'VARCHAR(30)', 'DOUBLE(11,10)', 'VARCHAR(30)', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT','TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT','TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT','TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT','TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT','TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT','TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT','TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT','TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT','TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT','TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT','TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT','TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'TINYTEXT',
                           'TINYTEXT', 'TINYTEXT', 'TINYTEXT', 'VARCHAR(30)', 'INT(10)', 'INT(10)',
                           'INT(10)'],
              'description':['title of project', 'center where project was performed', 'project identification',
                             'experiment identification', 'sample identification', 'run identification',
                             'platform sequencing was done on', 'model sequencing was done on', 'organism sequenced',
                             'sequence type', 'run identification', 'read count in base pairs', 'total base pair count',
                             'run identification', 'feature identification', 'kingdom classification', 'phylum classification',
                             'class classification', 'order classification', 'family classification', 'genus classification',
                             'species classification', 'confidence value of classification', 'sample identification',
                             'if subject has acid reflux', 'if subject takes acne medication', 'if subject takes OTC acne medication',
                             'if subject has ADD or ADHD', 'age category', 'age corrected value', 'age in years',
                             'if subject drinks alcohol', 'how often subject drinks alcohol', 'type of alcohol subject drinks',
                             'if subject drinks beer or cider', 'if subject drinks red wine', 'if subject drinks sour beers',
                             'if subject drinks hard alcohol', 'if subject did not specify the type of alcohol they drink',
                             'if subject drinks white wine', 'if subject has allergies', 'if subject does not have food allergies',
                             'if subject has other allergies not listed', 'if subject is allergic to peanuts',
                             'if subject is allergic to shellfish', 'if subject is allergic to tree nuts',
                             'if subject is allergic to an unspecified food', 'altitude of sample', 'if subject has alzheimers',
                             'if subject is anonymized', 'subject antibiotic history', 'if subject has had appendix removed',
                             'if subject uses artificial sweeteners', 'if subject has ASD', 'mimarks geographical value',
                             'if subject has autoimmune diagnosis', 'subject birth year', 'subject BMI', 'subject BMI category',
                             'subject BMI corrected', 'subject body habitat where sample was taken from', 'body product of sample',
                             'body site sample taken from', 'subject bowel movement frequency', 'subject bowel movement quality',
                             'if subject consumes mostly breast milk or formula', 'if subject has cancer',
                             'if subject is undergoing or has undergone cancer treatment', 'if subject has a cardiovascular disease',
                             'if subject lives with a cat', 'if subject has c diff', 'the census region of subject',
                             'if subject has had chickenpox', 'if subject has clinical condition not provided',
                             'collection date of sample', 'month of collection date', 'season of collection date',
                             'time on collection date', 'timestamp of collection', 'if subject eats animal products treated with antibiotics',
                             'if subject uses contraceptives', 'how often subject uses cosmetics', 'country from sample collection',
                             'country of subject birth', 'country of subject residence', 'if subject has had a c section',
                             'is subject uses deodorant', 'if subject has depression or bipolar disorder or schizophrenia',
                             'how often subject exercises', 'where subject exercises', 'subject source of food as infant',
                             'how often subject has fermented plants', 'how often subject flosses',
                             'time since subject received flu vaccine', 'how often subject has frozen desserts',
                             'how often subject has fruits', 'if subject has fungal overgrowth', 'geographical location name',
                             'is the subject gluten free', 'if subject has specimen left', 'subject height in cm',
                             'subject height units', 'how often subject has high fat red meat', 'how often subject has home cooked meals',
                             'common name of host', 'subject id of subject', 'tax id of subject', 'if subject has IBD',
                             'type of IBD diagnosis', 'sub IBD diagnosis classification', 'if subject has IBS',
                             'if subject has kidney disease', 'if subject is lactose intolerant', 'time since subject last moved',
                             'time since subject last travel', 'latitude of subject zip code', 'subject level of education',
                             'if subject has liver disease', 'if subject lives with others who also submitted samples',
                             'longitude of subject zip code', 'if subject follows low grain diet type', 'if subject has lung disease',
                             'how often subject has meat or eggs', 'if subject has mental illness diagnosis',
                             'type of mental illness', 'if subject has anorexia nervosa', 'if subject has bipolar disorder',
                             'if subject has bulimia nervosa', 'if subject has depression', 'if subject has PTSD',
                             'if subject has schizophrenia', 'if subject has substance abuse', 'if subject has unspecified mental illness',
                             'if subject has migraine diagnosis', 'how often subject has milk or cheese',
                             'how often subject has milk substitute', 'if subject takes multivitamins', 'if subject is a nail biter',
                             'if subject has non food allergies', 'if subject is allergic to beestings', 'if subject is allergic to drugs',
                             'if subject is allergic to pet dander', 'if subject is allergic to poison ivy',
                             'if subject is allergic to sun exposure', 'if subject is allergic to an unspecified non food allergy',
                             'frequency of olive oil use', 'how often subject drinks one liter of water per day',
                             'if subject has physical specimen remaining', 'if subject has PKU', 'frequency of pool use',
                             'how often subject has poultry', 'if subject is pregnant', 'how often subject has prepared meals',
                             'how often subject takes probiotics', 'if sample is public', 'subject race',
                             'how often subject has ready to eat meals', 'how often subject has red meat', 'if subject has roommates',
                             'if roommates are in this study', 'how often subject has salted snacks', 'sample type',
                             'how often subject has seafood', 'how often subject smokes', 'if subject uses fabric softener',
                             'if subject is on a specialized diet', 'if subject is on a diet that excludes dairy',
                             'if subject is on a diet that excludes nightshades', 'if subject is on a diet that excludes refined sugars',
                             'if subject is on a low fodmap diet', 'if subject is on a halaal diet',
                             'if subject does not follow a specialized diet', 'if subject follows a kosher diet',
                             'if subject follows a modified paleo diet', 'if subject follows other restrictive diet not listed',
                             'if subject follows a paleo or primal diet', 'if subject follows a raw food diet',
                             'if subject follows an unspecified diet', 'if subject follows a western price or other low grain or low processed diet',
                             'state of subject residence', 'age between 20 to 69', 'if subject has used antibiotics in the past year',
                             'if if subject has BMI between 18.5 and 30', 'if subject does not have diabetes', 'if subject is in health subset',
                             'if subject does not have IBD', 'how often subject has sugar sweetened drinks', 'how often subject has sugary sweets',
                             'survey identification', 'how often subject brushes their teeth', 'if subject has thyroid disorder', 'title of project',
                             'if subject has had tonsils removed', 'number of plant species subject has eaten within the past week',
                             'how often subject has vegetables', 'how often subject takes vitamin B supplement',
                             'how often subject takes vitamin D supplement', 'if subject has vivid dreams',
                             'if subjects weight has changed more than 10 lbs within the past year', 'weight in kilograms', 'weight units',
                             'how often subject has whole eggs', 'how often subject has whole grains', 'phylum name',
                             'number of phylum nucleotide sequences', 'number of phylum protein sequences', 'number of phylum punned citations']}

# printing out data dictionary
for each_row in zip(*([i] + (j)
                      for i, j in dictionary.items())):
    print(*each_row, " ")
